### ISSUE TITLE
future<void>::get() should not return a value

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.outcome#2]
Currently it returns `no_value_type`, not `void`.
Consider the generic use case, for example:

```c++
template<class T>
inline T await_resume(future<T>& fut)
{
    return fut.get();
}
```

Such code will fail to compile with `future<void>`.

**Comment by ned14** [comment]
Yes, correct. I need to fix this across the board actually as neither future nor monad return void properly from get(). It's on my todo after the AFIO review begins end of this week. Thanks for the report.
