### ISSUE TITLE
Rename basic_monad, monad_error, monad_category

### ISSUE THREAD

**Issue by ned14** [ned14/boost.outcome#20]
Suggestions made:
* `basic_monad` -> `outcome_base` or `basic_outcome`
* `monad_error` -> `bad_outcome` or `outcome_error`

Two votes were for `bad_outcome`, I do like the ring of it.

**Comment by viboes** [comment]
I'm all for the renaming. A monad is a concept, it is not something concrete.

**Comment by ned14** [comment]
I have renamed all the types in the public interface and docs which mention "monad" to something based on "outcome". Unfortunately changing `basic_monad` to `basic_outcome` is a very large amount of work, and as that type never appears in the public docs and is internal implementation only, I'm going to go ahead and skip that part for now.

**Comment by viboes** [comment]
It appears here

https://ned14.github.io/boost.outcome/classboost_1_1outcome_1_1v1__xxx_1_1expected.html

in the inheritance hierarchy

and here 
https://ned14.github.io/boost.outcome/classboost_1_1outcome_1_1v1__xxx_1_1basic__monad.html

I believe this issue should be re-open.
