### ISSUE TITLE
Missing make_ready_future()

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.outcome#3]
There's no `make_ready_future` for `future<void>`.

Besides, currently `make_ready_future(t)` is implemented as `future<T>(t)`, however, I'd suggest dropping such ctor for `future<T>`, consider the case for `future<void>`, there's no  corresponding ctor that makes it a ready future, `future<void>()`? no, the default constructed one is invalid. Such value-init ctor is confusing and inconsistent.

**Comment by ned14** [comment]
Thanks for the report. It is now fixed.
