### ISSUE TITLE
Incorrect continuation result for void return type

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.outcome#5]
The following program crashes:
```c++
ned::promise<int> p;
auto t = p.get_future();
t.then([](ned::future<int> const&) {});
p.set_value(0);
```

The reason is: in `future.hpp` line 771, it checks `v.is_ready()`, and in `monad.hpp` line 866, the return value is `output_type()`, which is incorrectly "not ready", it should return `output_type(value)` instead.

**Comment by ned14** [comment]
Many thanks for this bug report. However very shortly I'm going to remove the future-promise implementation entirely, I no longer need anything more than basic_monad and its non-concurrent derivatives as AFIO v2 no longer has any awareness of threads (or memory management, or exceptions, for that matter). Thanks for all the bug reports over the last few months though.

**Comment by jamboree** [comment]
Hmm, it's a pity. I thought you had a more ambitious goal for boost.outcome than just being a merely detail of AFIO. What would AFIO v2 look like, btw? I didn't find any example.

**Comment by ned14** [comment]
> Hmm, it's a pity. I thought you had a more ambitious goal for boost.outcome than just being a merely detail of AFIO.

I do, indeed 2017's conference circuit is likely to be all about Outcome. But Outcome's future promise support was designed and written for AFIO before peer review. Peer review was extremely clear people don't want anything like the AFIO v1 design. So I'm giving them what they want, and futures and promises, or memory management, or exceptions are not what they want.

> What would AFIO v2 look like, btw? I didn't find any example.

I summarise the changes at the front of:

20160421 ACCU Distributed Mutual Exclusion using Proposed Boost.AFIO
https://www.youtube.com/watch?v=elegewDwm64

The front page of https://ned14.github.io/boost.afio/ also has some detail of the differences under the "New in v2" column.
