### ISSUE TITLE
Does lightweight_futures support recursive chaining?

### ISSUE THREAD

**Issue by jamboree** [ned14/boost.outcome#6]
Consider the following use case:
```c++
ned::promise<int> p;
auto t = p.get_future();
for (int i = 0; i != 65536; ++i)
    t = t.then([](ned::future<int>&& t) { return t.get() + 1; });
p.set_value(0);
std::cout << "ans: " << t.get();
```

Every new `t` depends on its previous result, and since the first `t` is stalled, a long chain of continuation is constructed. The continuation is invoked when the result is set, as the result, the continuation chain is invoked in a tail recursion manner, and the depth in this example is big enough to cause stackoverflow.

The problem (stackoverflow) could be solved though, and I don't consider this a bug in this library, it's a design decision. It's ok that this library doesn't support such a use case and just document the limitation clearly.

What's the intended decision here?

**Comment by ned14** [comment]
The intended design was to coalesce memory allocation into a single allocation as much as possible, so the recursion was supposed to cause one single large allocation at the base of the continuation chain. basic_monad::bind() and next() is implemented the same way, but obviously executes synchronously and so doesn't have the same problem of recursion spiralling out of control. Whether of course the actual implementation is anywhere close to ideal or optimal is a totally separate matter, I can't say I am entirely happy with the implementation, rather it was "good enough". Most of what I am not happy with is in the future-promise implementation, and by disposing of that I simplify things considerably, especially with the new automated unit tests from monad using code generator I'm writing next.

Once again, many thanks for the bug reports. I hope this reaction isn't dis-spiriting to you.
