### ISSUE TITLE
Alternative TRY macros?

### ISSUE THREAD

**Issue by jeremysalwen** [ned14/boost.outcome#9]
http://ned14.github.io/boost.outcome/md_doc_md_03-tutorial_b.html#try_operation

it says 

> Unlike the try operator, the macro is not an expression so you can't write statements like if(BOOST_OUTCOME_TRY(var, expr)) as you can in Rust or Swift, this is due to a limitation of the C++ language (you can't return from functions in an expression).

However, I found this implementation of the TRY macro that seems to get around that issue: https://github.com/oktal/result

**Comment by ned14** [comment]
He uses the "compound statements" extension available in GCC and clang only. They're dangerous to use in C++, and of course it's a non-portable compiler specific extension.

Let me see if I can come up with a `BOOST_OUTCOME_TRYE(expr)` which is safe. Thanks for the idea.

**Comment by ned14** [comment]
I went for `BOOST_OUTCOME_TRYX(expr)` instead. I *think* it is safely written. Thanks for the idea.
